services:
  gateway:
    image: openresty/openresty:1.19.3.1-bionic
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./test-module/conf:/usr/local/openresty/nginx/conf
    environment: 
      REDIS_HOST: redis
  redis:
    image: redis
    ports:
      - 6379:6379
  app1:
    build: ./app
    environment: 
      APP_NAME: 'The Microservice'
    ports:
      - 3001:3000
  app2:
    build: ./app
    environment: 
      APP_NAME: 'The Monolith'
    ports:
      - 3002:3000